"""add_admin_fields

Revision ID: 452e4ae865be
Revises: b2c3d4e5f6a7
Create Date: 2026-07-02 09:14:11.544275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '452e4ae865be'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False, comment='学员ID'),
    sa.Column('action', sa.String(length=20), nullable=False, comment='操作: submit | approve | reject'),
    sa.Column('operator_id', sa.Integer(), nullable=False, comment='操作人ID'),
    sa.Column('reason', sa.Text(), nullable=True, comment='备注/理由'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_logs_created_at'), 'approval_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_logs_learner_id'), 'approval_logs', ['learner_id'], unique=False)
    op.create_index(op.f('ix_approval_logs_operator_id'), 'approval_logs', ['operator_id'], unique=False)
    op.add_column('learners', sa.Column('machine_approval_status', sa.String(length=20), nullable=False, comment='机器使用审批: none | pending | approved | rejected'))
    op.add_column('learners', sa.Column('machine_approval_at', sa.DateTime(), nullable=True, comment='审批时间'))
    op.add_column('learners', sa.Column('machine_approval_by', sa.Integer(), nullable=True, comment='审批人ID'))
    op.create_index(op.f('ix_learners_machine_approval_status'), 'learners', ['machine_approval_status'], unique=False)
    op.create_foreign_key(None, 'learners', 'users', ['machine_approval_by'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, comment='角色: learner | admin'))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'learners', type_='foreignkey')
    op.drop_index(op.f('ix_learners_machine_approval_status'), table_name='learners')
    op.drop_column('learners', 'machine_approval_by')
    op.drop_column('learners', 'machine_approval_at')
    op.drop_column('learners', 'machine_approval_status')
    op.drop_index(op.f('ix_approval_logs_operator_id'), table_name='approval_logs')
    op.drop_index(op.f('ix_approval_logs_learner_id'), table_name='approval_logs')
    op.drop_index(op.f('ix_approval_logs_created_at'), table_name='approval_logs')
    op.drop_table('approval_logs')
    # ### end Alembic commands ###
