"""init tables

Revision ID: d92840797b02
Revises: 
Create Date: 2026-06-22 17:27:30.608019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd92840797b02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID'),
    sa.Column('agent_name', sa.String(length=50), nullable=False, comment='Agent 名称'),
    sa.Column('status', sa.Enum('idle', 'running', 'completed', 'error', name='agent_status_enum'), nullable=False, comment='状态'),
    sa.Column('message', sa.String(length=500), nullable=True, comment='状态消息'),
    sa.Column('progress', sa.Float(), nullable=True, comment='进度 0-100'),
    sa.Column('input_data', mysql.JSON(), nullable=True, comment='输入数据'),
    sa.Column('output_data', mysql.JSON(), nullable=True, comment='输出数据'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_session_id'), 'agent_logs', ['session_id'], unique=False)
    op.create_table('feedback_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID'),
    sa.Column('learner_id', sa.String(length=36), nullable=False, comment='学习者 ID'),
    sa.Column('topic', sa.String(length=200), nullable=False, comment='题目主题'),
    sa.Column('question', sa.String(length=500), nullable=False, comment='题目内容'),
    sa.Column('user_answer', sa.String(length=500), nullable=True, comment='用户答案'),
    sa.Column('correct_answer', sa.String(length=500), nullable=True, comment='正确答案'),
    sa.Column('is_correct', sa.Float(), nullable=True, comment='是否正确 0/1'),
    sa.Column('heuristic_question', sa.String(length=500), nullable=True, comment='启发式追问'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_records_learner_id'), 'feedback_records', ['learner_id'], unique=False)
    op.create_index(op.f('ix_feedback_records_session_id'), 'feedback_records', ['session_id'], unique=False)
    op.create_table('learners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('education_background', sa.String(length=50), nullable=False, comment='学历背景'),
    sa.Column('major', sa.String(length=100), nullable=False, comment='专业方向'),
    sa.Column('work_experience_years', sa.Float(), nullable=True, comment='工作年限'),
    sa.Column('self_assessment', mysql.JSON(), nullable=True, comment='技能自评 {skill: level}'),
    sa.Column('learning_style', sa.String(length=20), nullable=True, comment='学习风格: visual/theory/practice'),
    sa.Column('goals', mysql.JSON(), nullable=True, comment='学习目标列表'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话 ID'),
    sa.Column('resource_type', sa.Enum('lecture', 'guide', 'test', name='resource_type_enum'), nullable=False, comment='资源类型'),
    sa.Column('content', sa.Text(), nullable=False, comment='生成内容'),
    sa.Column('topic', sa.String(length=200), nullable=False, comment='主题'),
    sa.Column('difficulty', sa.String(length=20), nullable=True, comment='难度等级'),
    sa.Column('sources', mysql.JSON(), nullable=True, comment='知识溯源列表'),
    sa.Column('review_score', sa.Float(), nullable=True, comment='审核评分 0-1'),
    sa.Column('review_passed', sa.Enum('pending', 'passed', 'failed', name='review_status_enum'), nullable=True, comment='审核状态'),
    sa.Column('retry_count', sa.Float(), nullable=True, comment='重试次数'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_session_id'), 'resources', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_session_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_table('learners')
    op.drop_index(op.f('ix_feedback_records_session_id'), table_name='feedback_records')
    op.drop_index(op.f('ix_feedback_records_learner_id'), table_name='feedback_records')
    op.drop_table('feedback_records')
    op.drop_index(op.f('ix_agent_logs_session_id'), table_name='agent_logs')
    op.drop_table('agent_logs')
    # ### end Alembic commands ###
